"""Public FP8 W8A8 Linear backend surface."""

from .config import (
    FP8ActivationQuantization,
    FP8LinearBackend,
    FP8LinearConfig,
    FP8LinearConfigurationError,
    FP8LinearGranularity,
)
from .fp8_linear import (
    FP8_ALIGNMENT,
    FP8W8A8Linear,
    FP8WeightQuantization,
    align_fp8_dimension,
    native_scaled_mm,
    quantize_fp8_per_row,
    quantize_fp8_weight_per_row,
)
from .registry import (
    FP8BackendSelection,
    FP8BackendSupport,
    FP8BackendUnavailableError,
    evaluate_native_scaled_mm_support,
    probe_native_scaled_mm,
    probe_torchao,
    resolve_fp8_linear_backend,
)
from .runtime import (
    FP8LinearRuntimeStats,
    FP8LinearStorageSummary,
    summarize_fp8_linear_storage,
    validate_ordinary_tensor_storage,
)
from .viditq_int8_linear import (
    ViDiTQLinearRuntimeStats,
    ViDiTQW8A8BF16Linear,
    ViDiTQWeightQuantization,
    ViDiTQWorkspace,
    align_viditq_rows,
    dequantize_viditq_weight,
    pad_viditq_rows,
    quantize_viditq_weight_asymmetric,
    validate_viditq_ordinary_storage,
)
from .viditq_registry import (
    VIDITQ_DEFAULT_ROOT,
    VIDITQ_M_ALIGNMENT,
    ViDiTQKernelSet,
    ViDiTQKernelUnavailableError,
    ViDiTQSupport,
    evaluate_viditq_device_support,
    evaluate_viditq_shape,
    require_viditq_shape,
    resolve_viditq_kernels,
)

__all__ = [
    "VIDITQ_DEFAULT_ROOT",
    "VIDITQ_M_ALIGNMENT",
    "ViDiTQKernelSet",
    "ViDiTQKernelUnavailableError",
    "ViDiTQLinearRuntimeStats",
    "ViDiTQSupport",
    "ViDiTQW8A8BF16Linear",
    "ViDiTQWeightQuantization",
    "ViDiTQWorkspace",
    "align_viditq_rows",
    "dequantize_viditq_weight",
    "evaluate_viditq_device_support",
    "evaluate_viditq_shape",
    "pad_viditq_rows",
    "quantize_viditq_weight_asymmetric",
    "require_viditq_shape",
    "resolve_viditq_kernels",
    "validate_viditq_ordinary_storage",
    "FP8_ALIGNMENT",
    "FP8ActivationQuantization",
    "FP8BackendSelection",
    "FP8BackendSupport",
    "FP8BackendUnavailableError",
    "FP8LinearBackend",
    "FP8LinearConfig",
    "FP8LinearConfigurationError",
    "FP8LinearGranularity",
    "FP8LinearRuntimeStats",
    "FP8LinearStorageSummary",
    "FP8W8A8Linear",
    "FP8WeightQuantization",
    "align_fp8_dimension",
    "evaluate_native_scaled_mm_support",
    "native_scaled_mm",
    "probe_native_scaled_mm",
    "probe_torchao",
    "quantize_fp8_per_row",
    "quantize_fp8_weight_per_row",
    "resolve_fp8_linear_backend",
    "summarize_fp8_linear_storage",
    "validate_ordinary_tensor_storage",
]
